#!/usr/bin/env bash
# script that installs Nginx server and redirects /redirect_me to
# another page
# The redirection must be a “301 Moved Permanently”
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/wendymunyasi permanent;/" /etc/nginx/sites-available/default
service nginx start
