#!/usr/bin/env bash
# script that installs Nginx server and redirects /redirect_me to
# another page
# The redirection must be a “301 Moved Permanently”
apt-get -y update
apt-get -y install nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=hQsZUVMwEls permanent;"
sed -i "s/server_name _;/$string/" /etc/nginx/sites-available/default
service nginx restart
