#!/usr/bin/env bash
# script to install and configure HAproxy on load balancer server
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get update
apt-get install haproxy=2.6.\*

# Enable HAProxy to be started by the init script.
sed -i '$aENABLED=1' /etc/default/haproxy

echo -e "frontend app_servers
	bind *:80
    mode http
	default_backend apps
backend apps
	balance roundrobin
	server 20639-web-01 3.227.217.150:80 check
	server 20639-web-02 3.95.27.202:80 check
	" >> /etc/haproxy/haproxy.cfg
service haproxy restart
