#!/usr/bin/env bash
# script to install and configure HAproxy on load balancer server

MY_ID=20639
CONFIG_FILE=/etc/haproxy/haproxy.cfg
INPUT_LINE="
frontend web_server
        bind *:80
        mode http
        default_backend appps

backend appps
        balance roundrobin
        option forwardfor # ensure forwarded request includes cleint ip
        server 20639-web-01 3.227.217.150
        server 20639-web-02 3.95.27.202
"

# check if hostname is correct
if [[ $(hostname) =~ ^$MY_ID-lb-[0-9]+ ]]; then
    echo 'hostname properly configured'
else
    >&2 echo 'hostname not configured properly...'
    >&2 echo 'please set hostname to pattern: 20639-lb-<server_id>...'
    >&2 echo 'Example: sudo hostnamectl set-hostname 20639-lb-<insert_server_id_here>'
fi

# check if HAProxy was previously configured
if [ "$(grep -o "$INPUT_LINE" $CONFIG_FILE | wc -l)" != 0 ]; then
	echo 'HAProxy already configured to script specs :)...'
	# restart HAProxy
	service haproxy restart
else
	# install HAProxy Version 2.6
    apt-get install -y software-properties-common
    add-apt-repository -y ppa:vbernat/haproxy-2.6
    apt-get -y update
    apt-get -y install haproxy=2.6.\*

	# configure HAProxyd

	printf "%s" "$INPUT_LINE" >> $CONFIG_FILE

	# start HAProxy
	service haproxy start
fi