#!/usr/bin/env bash
# This script displays messages when receiving signals

echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid;' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -rf /var/run/myscript.pid' SIGQUIT
while :
do
    echo "To infinity and beyond"
    sleep 2
done