#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

counter=1
while [ $counter -le 10 ]
do
    echo "Best School"
    if [[ "$counter" == '9' ]]
    then
        echo "Hi"
    fi
    ((counter++))
done
