#!/usr/bin/env bash
# script should run the whoami command under the user passed as an argument and make sure to try your script by passing different users
pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
